### ISSUE TITLE
Fixture_file_upload not working in combination with let_it_be helper

### ISSUE THREAD

**Issue by StefanGies99** [test-prof/test-prof#106]
### Tell us about your environment

**Ruby Version:**
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
RSpec
**TestProf Version:**
0.7.2
### What did you do?
When I do a controller specific test I wanted to attach a fixture to the model by basically calling fixture_file_upload during the controller tests. This is fine when using a let block for every test. However when I use this in combination with a let_it_be block it throws sometimes this strange error: 
```
 An error occurred in an `after(:context)` hook.
Failure/Error: transaction.rollback

NoMethodError:
  undefined method `rollback' for nil:NilClass
# -e:1:in `<main>'

ActiveRecord::RecordNotFound:
     Couldn't find Educator with 'id'=1
```
This is how my let blocks look like: 
`let_it_be(:educator, refind: true) { create :educator }` -> Runs fine within let block
/// Some other stuff
`let(:somemodel) { create :somemodel, avatar: fixture_file_upload(Rails.root.join('spec', 'fixtures', 'images', 'somelogo.png')) } `

### What did you expect to happen?
I expected that all the tests will pass regardless of use of fixture_file_upload or not. 

### What actually happened?
The Educator is dropped before I can actually call it in the next method.

**Comment by palkan** [comment]
> ActiveRecord::RecordNotFound:
     Couldn't find Educator with 'id'=1

Looks like `educator` is deleted from DB during the example group execution. Do you use `database_cleaner` or something else to clean the DB state in tests?

It could be helpful to see SQL logs (see https://test-prof.evilmartians.io/#/logging?id=instructions and `LOG=ar rspec ...`).

**Comment by palkan** [comment]
> I'm using the database_cleaner indeed.

Why do you need it?)

You should either remove `config.around(:each) { ... }` or `config.use_transactional_fixtures = true`–the doing exactly the same with this setup.

**Comment by yasuf** [comment]
@StefanGies99 how did you fix this issue?
