### ISSUE TITLE
Saving reports to file for later analysis

### ISSUE THREAD

**Issue by gtrias** [test-prof/test-prof#113]
I'm using your gem to analyze a huge project and I'm wondering if there's an option to collect all Profiler's results into plain text files for later analysis. 

Right now all the results are outputted to stdout and are not handy to be managed when are executed in CI. I wish to have it in plain files and get it from CI as artifacts.

Any idea? Thank you :)

**Comment by palkan** [comment]
That’s something I have in the backlog (https://github.com/palkan/test-prof/projects/1#card-9778994), but haven’t started working on yet.

Could you please share your ideas on how do you want to use these files? Which format do you suggest to use?

**Comment by gtrias** [comment]
Great news!
Initially I only want some place to store all reports executed for each commit and navigate between them. The same format as the current printed ones would be good to start with something. But ideally It would be great to have a json to consume and make a basic UI to easy extract interesting parts. 

I'm very interested in track the test performance evolution and, having this data, I can manage to draw some graphs and numbers to prioritize those parts which has worst performance.

Do you have ETA for this functionality?

**Comment by palkan** [comment]
> Do you have ETA for this functionality?

Sorry, for late response.

No, no ETA as for today; I can start working on this feature in 2-3 weeks, and will provide updates here.

**Comment by palkan** [comment]
> there's an option to collect all Profiler's results into plain text files for later analysis.

It's now possible by specifying custom output device or even logger. E.g.:

```ruby
TestProf.configure do |config|
  config.output = ENV["TEST_PROF_REPORT_PATH", File.join(config.output_dir, "report.txt"))
  # or 
  config.logger = Logger.new(some_file)
end
```
