### ISSUE TITLE
ActiveRecord Shared Connection exposes feature spec race condition in Rails <5?

### ISSUE THREAD

**Issue by bubaflub** [test-prof/test-prof#179]
First of all, I wanted to say thank you for the excellent Gem and documentation and tutorials!  We're beginning to use `test-prof` and friends at work to reduce CI times and have already seen significant speed ups.

I'm not sure this is a bug in test-prof's Shared Connection recipe but I wanted to at least document what is a possible incompatibility.

### Tell us about your environment

**Ruby Version:**

MRI 2.4.9, running on Mac OS X 10.15.3 in dev and on CI inside a docker image `circleci/ruby:2.4.9-node-browsers:ae5c01547e6587520460dcc07d76ac898d45a5a16b5904a05b058ab4ac93036b`

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**

  * Rails 4.2.11.1
  * RSpec 3.9.0
  * FactoryBot 5.1.1
  * mysql2 0.5.3 connecting to MySQL 5.6.47

**TestProf Version:**

test-prof 0.11.3

### What did you do?

Since we have a large suite of Capybara feature specs I've tried to use `test_prof/recipes/active_record_shared_connection` to force both the server thread and the test thread to use the same DB connection so we could get use transactional fixtures instead of Database Cleaner's truncation strategy.

I added `require 'test_prof/recipes/active_record_shared_connection'`, removed `database_cleaner` and all related configuration, and set `config.use_transactional_fixtures = true`.

### What did you expect to happen?

The good news -- on our slowest feature spec the run time dropped from ~11 minutes to 4.5 minutes with this change and one other fix motivated by `TEST_RUBY_PROF=1`.

### What actually happened?

Bad news: tons of failures in CI. At first I thought it was due to a difference between dev and CI test environments (such as `config.eager_load = true`) but I was eventually able to replicate the failures locally.  I could get failures every time though the failures themselves could vary which led me to believe that the root cause was timing-dependent.  First failure in the run seemed most suspicious:

```
     ActiveRecord::StatementInvalid:
       Mysql2::Error: SAVEPOINT active_record_1 does not exist: RELEASE SAVEPOINT active_record_
     # /Users/bob/.rvm/gems/ruby-2.4.9/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
     # /Users/bob/.rvm/gems/ruby-2.4.9/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
     # /Users/bob/.rvm/gems/ruby-2.4.9/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
     # /Users/bob/.rvm/gems/ruby-2.4.9/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
     # /Users/bob/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
...
```

As part of vetting the shared connection change I turned on MySQL's general log with `SET GLOBAL general_log = 'on';`, puzzled for a bit to figure out where homebrew would put MySQL logs, and then watched the log during the spec run with `tail -f /usr/local/var/mysql/Bobs-MacBook-Pro.log`:

```
200228  0:04:20  1404 Query     SHOW FULL FIELDS FROM `users`
200228  0:04:21  1404 Query     SHOW CREATE TABLE `users`
200228  0:09:26  1404 Query     BEGIN
...
```

First column is date in YYMMDD, second column is local time, and the column is a database connection ID.  I can confirm that with the shared connection recipe included I'm seeing only one connection when the feature spec runs.  So that part is definitely working.

Since MySQL doesn't support nested transactions ActiveRecord uses `SAVEPOINT`s when we are already inside a transaction.  I believe `config.use_transactional_fixtures = true` is wrapping the entire spec file (or maybe the entire test suite run) in a transaction:

```
		 1467 Query	SET  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483, @@SESSION.sql_mode = 'STRICT_ALL_TABLES'
		 1467 Query	select max(version) from schema_migrations
		 1467 Query	BEGIN
...
```

And any other transactions are translated to SQL as `SAVEPOINT` and `RELEASE SAVEPOINT`:

```
		 1467 Query	SAVEPOINT active_record_1
...
		 1467 Query	RELEASE SAVEPOINT active_record_1
```

In my DB log file I never see an `active_record_2` or any other named `SAVEPOINT`.  And most of the time the log shows these coming in "balanced pairs": the pattern is `SAVEPOINT active_record_1`, one or more SQL queries, then `RELEASE SAVEPOINT active_record_1`.

But I do see one set that isn't balanaced:

```
		 1467 Query	SAVEPOINT active_record_1
		 1467 Query	SAVEPOINT active_record_1
		 1467 Query	INSERT INTO ...
		 1467 Query	INSERT INTO ...
		 1467 Query	RELEASE SAVEPOINT active_record_1
		 1467 Query	RELEASE SAVEPOINT active_record_1
```

It's this second `RELEASE SAVEPOINT` that is raising the DB error and I believe is the root cause of the failure.

For more debugging I installed and configured a Gem called [`active_record_query_trace`](https://github.com/brunofacca/active-record-query-trace) which logs a ruby backtrace any time ActiveRecord hits the database.  I looked in the test server logs for the corresponding queries.  Here's the double `SAVEPOINT` create:

```
D, [2020-02-27T21:25:42.807275 #76714] DEBUG -- : [4ed5405f-142c-4980-8d55-0df4e2ad23e3] [u:3629]   SAVEPOINT active_record_1
D, [2020-02-27T21:25:42.807641 #76714] DEBUG -- : [4ed5405f-142c-4980-8d55-0df4e2ad23e3] [u:3629] Query Trace:
      lib/redacted.rb:16:in `log_request'
      lib/redacted.rb:478:in `log_request'
      lib/redacted/redacted.rb:18:in `now'
      app/models/redacted.rb:128:in `begin_status_pull_for'
      app/services/redacted/redacted.rb:18:in `call'
D, [2020-02-27T21:25:42.809161 #76714] DEBUG -- :    SAVEPOINT active_record_1
D, [2020-02-27T21:25:42.809589 #76714] DEBUG -- : Query Trace:
      spec/features/redacted.rb:1185:in `block (4 levels) in <top (required)>'
      spec/features/redacted.rb:1188:in `block (4 levels) in <top (required)>'
      spec/rails_helper.rb:276:in `block (2 levels) in <top (required)>'
      spec/rails_helper.rb:197:in `block (2 levels) in <top (required)>'
      spec/rails_helper.rb:177:in `block (3 levels) in <top (required)>'
```

Our Rails logger is configured to generate a UUID for each incoming request and tag all logs created as part of serving the response with the same UUID.  What's notable to me:

  * The first set of logs has a UUID and is coming from application code.
  * The second set of logs does not have a UUID and is coming from test code.
  * The first set of logs indicates that we have begun doing a psuedo-nested transaction but have not completed it yet.  The second set of logs then starts in the middle and seems to be unaware that we are already in a `SAVEPOINT` named `active_record_1`.

After some expected `INSERT` and `SELECT` queries I see these logs:

```
D, [2020-02-27T21:25:42.813719 #76714] DEBUG -- : [4ed5405f-142c-4980-8d55-0df4e2ad23e3] [u:3629]  RELEASE SAVEPOINT active_record_1
D, [2020-02-27T21:25:42.814059 #76714] DEBUG -- : [4ed5405f-142c-4980-8d55-0df4e2ad23e3] [u:3629] Query Trace:
      lib/redacted/redacted.rb:16:in `log_request'
      lib/redacted.rb:478:in `log_request'
      lib/redacted/redacted.rb:18:in `now'
      app/redacted/redacted.rb:128:in `begin_status_pull_for'
      app/services/redacted/redacted.rb:18:in `call'
D, [2020-02-27T21:25:42.815412 #76714] DEBUG -- :   RELEASE SAVEPOINT active_record_1
D, [2020-02-27T21:25:42.815866 #76714] DEBUG -- : Query Trace:
      spec/features/redacted.rb:1185:in `block (4 levels) in <top (required)>'
      spec/features/redacted.rb:1188:in `block (4 levels) in <top (required)>'
      spec/rails_helper.rb:276:in `block (2 levels) in <top (required)>'
      spec/rails_helper.rb:197:in `block (2 levels) in <top (required)>'
      spec/rails_helper.rb:177:in `block (3 levels) in <top (required)>'
```

Here we see the logs for the double `RELEASE SAVEPOINT active_record_1` that is generating our test failure.  Same pattern as above: the first logs have a UUID (the same as the first set in the first group of logs) and the second set of logs don't have a UUID.  The backtraces for each group is also identical.

Relevant lines of code:

`lib/redacted/redacted.rb:16` in `log_request':

```
foo.save!
```

Where `foo` is an instance of an ActiveModel object.  It doesn't have any custom `save!` logic.  It has an `after_save` hook that will log but does no database updates.

`spec/features/redacted.rb:1185`:

```
let(:foo) { create :thing, status: OTHER_THING }
```

Where `thing` is a FactoryBot factory.  It has multiple associations that will cascade to other factories to create objects.  `OTHER_THING` is a constant string value.

This feature spec is driving a headless chrome browser using Capybara.  The feature spec will include many AJAX calls which means we can have multiple independent requests in-flight at the same time.  However, Capybara is configured to serve tests with the `webrick` server, which I believe is single-threaded.  We have not called `threadsafe!` in our application config and we do not spawn any threads during these test runs.

I considered if we needed to call `.transaction` with `joinable: false` or `requires_new: true` or both.  But a few things make me think this isn't the problem:

  * We never see this problem without the shared connection recipe.
  * Neither parts of code are in explicit transactions.  They are only in implicit transactions.
  * Neither inner SQL queries are doing things in MySQL that implicitly cause a transaction commit, like DDL schema changes.
  * If there was a problem with nesting transactions I'd expect to see a problem with ordering like:
       ```
       SAVEPOINT active_record_1
       SAVEPOINT active_record_2
       RELEASE SAVEPOINT active_record_1
       RELEASE SAVEPOINT active_record_2
       ```
  
But what I'm seeing is that two separate places are trying to use the same underlying connection at what seems like the same time and they both determined that they were `SAVEPOINT active_record_1`.  This seems to me more like a synchronization issue.

My current hypothesis is that the shared connection recipe does exactly what it says: all feature spec test threads are now sharing the same DB connection.  But I think as an unintended side-effect this has exposed a synchronization bug or race condition in Rails.  Specifically, I think to use this safely with Rails 4.2 I'd need the changes in https://github.com/rails/rails/pull/28726.

I think I need those changes because of the following back-and-forth when the DB connection sharing feature was implemented in Rails:

  * Original PR that implemented shared connections for spec threads: https://github.com/rails/rails/pull/28083
  * Report that the new sharing connection behavior can break existing tests, recommended to set `self.use_transactional_tests = false` to avoid problems: https://github.com/rails/rails/issues/28466
  * Report indicating that the shared connections for spec threads has broken existing tests, with a different error being returned to the user: https://github.com/rails/rails/issues/29164
  * Report with the same issue as mine but running against Postgres, suspects that the original changes to share connections between threads could be the culprit: https://github.com/rails/rails/issues/28197
  * Rejected PR that added more synchronization to active record connection sharing across spec threads, has a good description of the problem: https://github.com/rails/rails/pull/28605
  * PR that actually made it in to Rails 5.1 to add synchronization around shared connections: https://github.com/rails/rails/pull/28726

Looking through the code of that last PR and reading the description it seems like this could fix exactly what I'm seeing -- a shared DB connection being used simultaneously from two different places at the same time stepping on each other.  From the CHANGELOG description at https://github.com/rails/rails/commit/90a3ce293defbad5cbb2688f09a566be2c50410f:

> When multiple threads are sharing a database connection inside a test using
> transactional fixtures, a nested transaction will temporarily lock the
> connection to the current thread, forcing others to wait.

If you've made it this far, I'd like to thank you for attending my TED talk.

And to conclude, I think the test-prof recipe itself is fine but can be unsafe for feature specs without the synchronization provided by https://github.com/rails/rails/pull/28726 which lands in Rails 5.1.  If we're on Rails 5.1 we don't need the recipe and I'm unsure if this change be monkey patched in.  So if my hypothesis is correct we might want to warn folks that this can cause goofy behavior on earlier (now-EOL'd) versions of Rails.

**Comment by palkan** [comment]
> If you've made it this far, I'd like to thank you for attending my TED talk.

😂

> I think to use this safely with Rails 4.2 I'd need the changes in rails/rails#28726.

Yeah, looks like the `@stack.size` issue. Not sure, why we haven's seen this before. Probably there is a MySQL adapter specific issue (we only used this recipe with PostgreSQL).

Need more time to think about it. Thanks for such a detailed and breathtaking report!

**Comment by bubaflub** [comment]
Hello again!  We've just updated to Rails 5.1 and though we no longer need the shared connection recipe since those fixes are in Rails itself there are *additional* synchronization bugs with Rails 5.1, `mysql2`, and `transactional_fixtures`. I thought I'd put some notes here to help other folks out.

With Rails 5.1, `transactional_fixtures = true`, and the `mysql2` Gem I started seeing Capybara + selenium feature spec failures.  Capybara alone (i.e. running `Rack::Test`) won't trigger this since everything will run on the same thread. (See https://github.com/teamcapybara/capybara/#transactions-and-database-setup for details.)

I believe this is also specific to the `mysql2` Gem as it looks like `mysql2` isn't really thread-safe nor is it designed to be (see https://github.com/brianmario/mysql2/issues/886#issuecomment-326077782).  That's probably why you don't see this with the PostgreSQL DB adapter.  And look, another reason to use PostgreSQL over MySQL!

So with our magical mixtures of Rails 5.1, a feature spec with Capybara and selenium, and the `mysql2` Gem most things work.  But some things don't.  And the errors I got were the profoundly unhelpful: `Mysql2::Error` with no further information.  Behold:

```
      10.1) Failure/Error: update_column(redacted, DateTime.current)
﻿ ﻿           Mysql2::Error:
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql/database_statements.rb:43:in `affected_rows'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql
/database_statements.rb:43:in `block in exec_delete'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstr
act_mysql_adapter.rb:223:in `execute_and_free'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql
/database_statements.rb:43:in `exec_delete'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstr
act/database_statements.rb:140:in `update'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstr
act/query_cache.rb:17:in `update'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/relation.rb:380:in `updat
e_all'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/persistence.rb:330:in `up
date_columns'
            # /Users/bob/.rvm/gems/ruby-2.5.8/gems/activerecord-5.1.7/lib/active_record/persistence.rb:303:in `up
date_column'
            # ./app/models/redacted.rb:9:in `redacted!'
```

Like, isn't that exactly where a helpful error message should be?  😢 

The `update_column` call and the backtrace lead me to https://github.com/rails/rails/issues/34798 and the PR https://github.com/rails/rails/pull/34800/files which lands in Rails 6.  With a similar file to https://github.com/rails/rails/issues/34798#issuecomment-480015188 to monkey patch around this issue my feature specs no longer fail for this mysterious `Mysql2::Error`.  (Now they fail because we have years of hard-coding IDs and assuming the DB completely resets between feature spec runs.  Hooray, progress!)

I guess `test-prof` could include even more monkey patches to work around all of these issues.  Or it could just warn folks that with `mysql2` things aren't going to work until Rails 6.

**Comment by palkan** [comment]
Hey @bubaflub!

Thanks again for your investigation. Unfortunately, I have to close this issue unresolved: we're dropping support for older Rails in v1.0, thus, making `active_record_shared_connection` useless. It served us well, but it's time to say good-bye.
