### ISSUE TITLE
using let_it_be and before_all rspec time to run and time to load are completely off

### ISSUE THREAD

**Issue by danielnc** [test-prof/test-prof#189]
**Ruby Version:** ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rspec

**TestProf Version:** 0.11.3

### What did you do?
`$ time (rspec spec/model_spec.rb)` and compared zsh time and rspec total time

### What did you expect to happen?
I would expect that time to load + rspec run time to be near `time` output. but it's really far from the other. 

Total time if you sum: ~ 5.9s
`$ time `:  5.903

```bash
Finished in **5.43 seconds&& (files took 0.47438 seconds to load)
40 examples, 0 failures

Randomized with seed 39419
( bundled_rspec spec/model_spec.rb; )  0.62s user 0.59s system 20% cpu 5.903 total
```
### What actually happened?
They are really far from the other. 

Total time if you sum: 4.45s
`$ time `:  5.903

```bash
Finished in **3.98 seconds&& (files took 0.47438 seconds to load)
40 examples, 0 failures

Randomized with seed 39419
( bundled_rspec spec/model_spec.rb; )  0.62s user 0.59s system 20% cpu 5.903 total
```

**Comment by palkan** [comment]
Could you please provide a bit more information about your setup? Which TestProf files do you require etc.

Do you use example state persistence? That's one of things RSpec [does after all the reporting](https://github.com/rspec/rspec-core/blob/d730c023b0765ffeaa5becb80f17e1fc02d2f9d1/lib/rspec/core/runner.rb#L90), thus, it is not included in RSpec total time.

**Comment by palkan** [comment]
Closed as stale
