### ISSUE TITLE
let_it_be leads to ActiveRecord invalid savepoint issues in Rails3

### ISSUE THREAD

**Issue by intrip** [test-prof/test-prof#197]
### Tell us about your environment

**Ruby Version:**

`2.3.4`

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**

`Rspec 3.7.0`
`Rails 3.2.22.5`
`Mysql 5.7`

**TestProf Version:**

`0.7.5`

### What did you do?

Using `let_it_be` within the specs in the following way: `let_it_be(:user) { create(:user) }`

### What did you expect to happen?

I expected `let_it_be` to correctly create the record and roll it back afterwards.

### What actually happened?

The following error occured:

` ActiveRecord::StatementInvalid:
     Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1`

### Possible solutions

This error occurs when ActiveRecord tries to rollback to a SAVEPOINT which doesn't exists.
After some checks I've figure out that in https://github.com/test-prof/test-prof/blob/master/lib/test_prof/ext/active_record_3.rb#L8 
we always call `increment_open_transactions `, this leads to always reaching https://github.com/test-prof/test-prof/blob/master/lib/test_prof/ext/active_record_3.rb#L10 **no matter if we are within a transaction or not**. 
Due to the above this method incorrectly creates a `savepoint` when no transactions are currently running which leads to the invalid savepoint issue.
I've monkey patched this locally but just moving line 8 below the `if open_transactions > 0` check and the issue was solved.

If you agree on my proposal I'll make a PR.

**Comment by palkan** [comment]
Thanks for the report!

> If you agree on my proposal I'll make a PR.

Yes, please.

We plan to drop Rails 3 support in 1.0 but we still have time to release the patch in the 0.12.x series.
