### ISSUE TITLE
Docs coggle links: recipe links now out of date

### ISSUE THREAD

**Issue by olleolleolle** [test-prof/test-prof#207]
### Tell us about your environment

**Ruby Version:** n/a

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** n/a

**TestProf Version:** n/a

### What did you do?

I navigated to the AnyFixture link in [the (very nice) coggle mindmap](http://bit.ly/test-prof-map) and it took me to a 404.

### What did you expect to happen?

Expected:

https://test-prof.evilmartians.io/#/recipes/any_fixture?id=anyfixture which is current

### What actually happened?

Actual:

https://test-prof.evilmartians.io/#/any_fixture which is a 404

**Comment by palkan** [comment]
Thanks for reporting!

Fixed. The link has changed: http://bit.ly/test-prof-map-v1
