### ISSUE TITLE
Spring detection does not work when spring is in Gemfile but DISABLE_SPRING=1

### ISSUE THREAD

**Issue by grk** [test-prof/test-prof#215]
### Tell us about your environment

**Ruby Version:** 2.7.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rails 6.1.3.2, RSpec 3.10.0

**TestProf Version:** 1.0.5

### What did you do?
Run rspec with e.g. FPROF=1

### What did you expect to happen?
Get profiling output

### What actually happened?
The tests ran, I saw a "spring detected" line from test prof, but no profiling output.

Running the tests with spring enabled, or removing spring from Gemfile solves the problem.

I tried digging around spring internals to see if there's an easy way to look for to check if spring is actually enabled but didn't find anything.

**Comment by palkan** [comment]
Probably, checking for `DISABLE_SPRING` could be enough.

> I tried digging around spring internals to see if there's an easy way to look for to check if spring is actually enabled but didn't find anything.

Could you please point to the place where they check for `DISABLE_SPRING`?

**Comment by grk** [comment]
I think it's only here: https://github.com/rails/spring/blob/577cf01f232bb6dbd0ade7df2df2ac209697e741/lib/spring/binstub.rb

**Comment by grk** [comment]
Awesome, thank you!
