### ISSUE TITLE
FactoryDoctor did not trigger on the most heavy spec

### ISSUE THREAD

**Issue by TiSer** [test-prof/test-prof#221]
> NOTE: have you noticed the "potentially" word? Unfortunately, FactoryDoctor is not a magician (it's still learning) and sometimes it produces false negatives and false positives too.
> Please, submit an issue if you found a case which makes FactoryDoctor fail.

### Tell us about your environment

**Ruby Version: 2.6.6**

**Framework Version: (RSpec 4, FactoryBot 5, Rails 4):**

**TestProf Version: 1.0**

### What did you do?

I've run FactoryDoctor on my slowest spec, that I found by `EventProf` with `factory.create`:

> Top 5 slowest tests (by time):
> is expected n...tChange.count` (./spec/workers/data_cleaners/remove_histories_worker_spec.rb:16) – 00:07.008 (4) of 00:07.052 (99.38%)
> is expected t...e.count` by -2 (./spec/workers/data_cleaners/remove_histories_worker_spec.rb:38) – 00:06.128 (4) of 00:06.216 (98.58%)
> returns price error (./spec/controllers/backoffice/api/products_controller_spec.rb:285) – 00:06.027 (2) of 00:06.360 (94.76%)
> is expected t...e.count` by -1 (./spec/workers/data_cleaners/remove_histories_worker_spec.rb:27) – 00:06.020 (4) of 00:06.079 (99.02%)
> is expected t...e.count` by -1 (./spec/workers/data_cleaners/remove_histories_worker_spec.rb:26) – 00:05.942 (4) of 00:05.999 (99.06%)

Here is the time stats made by `--profile` with RSpec:

> Top 6 slowest examples (29.98 seconds, 98.9% of total time):
>   DataCleaners::RemoveOrderHistoriesWorker#perform when present records to destroy is expected to change `History::ProductChange.count` by -1
>     11.13 seconds ./spec/workers/data_cleaners/remove_histories_worker_spec.rb:27
>   DataCleaners::RemoveOrderHistoriesWorker#perform when present records to destroy is expected to change `History::OrderChange.count` by -1
>     4.94 seconds ./spec/workers/data_cleaners/remove_histories_worker_spec.rb:26
>   DataCleaners::RemoveOrderHistoriesWorker#perform when no records to destroy is expected not to change `History::ProductChange.count`
>     4.67 seconds ./spec/workers/data_cleaners/remove_histories_worker_spec.rb:16
>   DataCleaners::RemoveOrderHistoriesWorker#perform when all records should be destroyed is expected to change `History::OrderChange.count` by -2
>     4.64 seconds ./spec/workers/data_cleaners/remove_histories_worker_spec.rb:37
>   DataCleaners::RemoveOrderHistoriesWorker#perform when all records should be destroyed is expected to change `History::ProductChange.count` by -2
>     4.6 seconds ./spec/workers/data_cleaners/remove_histories_worker_spec.rb:38
>   DataCleaners::RemoveOrderHistoriesWorker#perform should be in default queue is expected to be processed in the "backoffice_default" queue
>     0.00133 seconds ./spec/workers/data_cleaners/remove_histories_worker_spec.rb:7

So, it's very slow.

But when I've run FactoryDoctor on that spec, it said "Looks good to me!".

The cause was the factories cascade creation, that was described in your [article](https://evilmartians.com/chronicles/testprof-2-factory-therapy-for-your-ruby-tests-rspec-minitest). So, I've left my factories within the suite for my base objects, but instead of all cascade associations, I've assigned to base objects `build_stubbed` associated objects and achieved 50% of speed up.

### What did you expect to happen?

I expect FactoryDoctor will trigger on my problematic spec, which was the most heavy within whole application.

### What actually happened?

FactoryDoctor said: _[TEST PROF INFO] FactoryDoctor says: "Looks good to me!"_

**Comment by palkan** [comment]
FactoryDoctor is only able to identify tests, which do no use database outside of factories (i.e., when you create objects but never modify them or perform queries).

For cascade detection you should use [FactoryProf](https://test-prof.evilmartians.io/#/profilers/factory_prof).
