### ISSUE TITLE
StackProf integration: outputted flamegraph generator command broken

### ISSUE THREAD

**Issue by prostko** [test-prof/test-prof#222]
### Tell us about your environment

**Ruby Version:**
 2.6.5

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
Rails 4.2.11.3

**TestProf Version:**
1.0.7 

**StackProf Version**  
  stackprof (0.2.17)

### What did you do?
Attempting to profile boot time -> `TEST_STACK_PROF=boot be rspec spec/services/`

which ran successfully, creating `tmp/test_prof/stack-prof-report-wall-raw-boot.dump` as expected. However, as you know, this is just data. The flamegraph isn't generated yet. Super helpfully (love this gem, y'all) you out put the command to go ahead and generate that viewable flamegraph. This is the bug, at least for me.

```
stackprof --flamegraph tmp/test_prof/stack-prof-report-wall-raw-total.dump > tmp/test_prof/stack-prof-report-wall-raw-total.html && stackprof --flamegraph-viewer=tmp/test_prof/stack-prof-report-wall-raw-total.html
```

### What did you expect to happen?

I expected the generated file `...html` to be viewable in the browser.

### What actually happened?

When I run this command, it populates .`..html` with a ton of data, ```flamegraph({ <data> })``` but that isn't viewable at all, not in chrome, brave, firefox or safari.
 

### Suggestion

(Happy to submit a PR as well)

Quick look at StackProf docs, and trying the commands they give, some of which didn't work -- generating a flamegraph with the D3 flag worked like a charm, and everything came out nice just like the FactoryProfiler graphs.

`stackprof --d3-flamegraph tmp/test_prof/stack-prof-report-wall-raw-total.dump > tmp/test_prof/stack-prof-report-wall-raw-total.html`

Again, thanks y'all love your work. Really appreciate what you do.

**Comment by palkan** [comment]
Thanks for suggestion! Updated.

**Comment by mnawalali** [comment]
i am facing the same issue
