### ISSUE TITLE
Issue with configuring output location

### ISSUE THREAD

**Issue by zormond** [test-prof/test-prof#245]
### Tell us about your environment

Ruby: 2.7.4

Rspec 3.9

Test Prof 1.0.7

### What did you do?

I tried to configure the output of test_prof to a file like this

```
TestProf.configure do |test_prof_config| 
  test_prof_config.output_dir = 'test_prof'
  test_prof_config.output = File.join(test_prof_config.output_dir, "report.txt")
  test_prof_config.color = false
end
```

### What did you expect to happen?

I expected the output of test_prof to be output to the file.

### What actually happened?

It is still output to STDOUT

### What I tried to do:

From the debugging I did, it seemed that the logger in the configuration object is getting initialized with STDOUT. Since the logger attribute is using a conditional assignment operator, it always returns this logger even after I try to update the output on the configuration object.

```
class Configuration
    attr_accessor :output, # IO to write logs
      :color, # Whether to colorize output or not
      :output_dir, # Directory to store artifacts
      :timestamps, # Whether to use timestamped names for artifacts,
      :report_suffix # Custom suffix for reports/artifacts

    def initialize
      @output = $stdout
      @color = true
      @output_dir = "tmp/test_prof"
      @timestamps = false
      @report_suffix = ENV["TEST_PROF_REPORT"]
    end

    ...

    def logger
      @logger ||= Logger.new(output, formatter: Logging::Formatter.new)
    end
  end
```

I added this just to see if it works, and it does:

```
def output=(value)
  if value != $stdout
    @logger = Logger.new(value, formatter: Logging::Formatter.new)
  end
end
```

**Comment by palkan** [comment]
Thanks for the report!

Where do you put the configuration block? It's assumed that no `logger` calls are made prior to the initial configuration (so, the next time it's lazily evaluated, the output is correct).

**Comment by zormond** [comment]
Yeah that makes sense.

I'm in a rails project right now and I'm putting it in the config/environments/test.rb configuration file. 

Maybe that's my problem? Maybe it should go somewhere else?

The config file looks like this:

```
Rails.application.configure do
  TestProf.configure do |test_prof_config| 
    # ... other configs ... #
    test_prof_config.output_dir = 'test_prof'
    test_prof_config.output = File.join(test_prof_config.output_dir, "report.txt")
    test_prof_config.color = false
  end
end
```

**Comment by palkan** [comment]
Yeah, you should put it in your `rails_helper.rb` / `test_helper.rb`

**Comment by zormond** [comment]
Thanks. Let's chalk this one up to weird project configuration.

**Comment by nialbima** [comment]
I'm having this issue as well. I've moved my config call out of `spec/support/test_prof` and into `rails_helper`, as suggested. It looks like this: 

```
TestProf.configure do |config|
  if ENV['ANALYZING_SPECS']
    runner_name = "runner_#{ENV['TEST_ENV_NUMBER'].presence || 1}"
    output_dir = "#{ENV['TEST_PROF_REPORTS_DIR']}/#{runner_name}"

    config.output_dir = output_dir
    config.output = File.join(config.output_dir, 'test-prof-output.txt')
    config.color = false
    config.timestamps = false
  end
end
```

We're using parallel_specs and I'm trying to capture the results of each parallel spec run so I can combine them into a shareable doc. I can always pipe the output and parse the text, which is what I'm doing now, but it's not ideal.
