### ISSUE TITLE
Rails fixtures in before_all do not work with rspec-rails

### ISSUE THREAD

**Issue by codez** [test-prof/test-prof#261]
### Tell us about your environment

**Ruby Version:** 2.7.7

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rspec 3.12.0, Rails 7.0.4.1, Rspec-Rails 6.0.1

**TestProf Version:** 1.1.0

### What did you do?

I globally configured Rails fixtures for `before_all` using `config.setup_fixtures = true`.  Then I wanted to use fixtures in a `let_it_be` block (e.g. `let_it_be(:user) { create(:user, group: groups(:main)) }`)

### What did you expect to happen?

A user with the group from the Rails fixtures is created.

### What actually happened?

The user is created without a group, i.e. `groups(:main)` prints the warning "Calling fixture method in before :context" and returns `nil`.  This behavior comes from [rspec-rails](https://github.com/rspec/rspec-rails/blob/ce70c2fbdf9c666217490f091b2ee6bda5e2772b/lib/rspec/rails/fixture_support.rb#L49).

I could patch above line as following, so that the original implementation is called as expected when we are in a before all hook:

```ruby
if RSpec.current_scope == :before_context_hook && @__inspect_output != 'before_all hook'
```

**Comment by palkan** [comment]
Thanks for the report. I will take some time for me to remember how `setup_fixtures = true` works and should work; not sure if it's gonna be a quick fix.

**Comment by palkan** [comment]
Okay, I narrowed it down to this change in `rspec-rails`: https://github.com/rspec/rspec-rails/commit/6489ae63c5150ecad1e35f4afd8862e965f9b061

Earlier version of `rspec-rails` should work as expected. (You can check while I'm working on a fix)
