### ISSUE TITLE
Not compatible with ruby-prof >= 1.4.0?

### ISSUE THREAD

**Issue by mateomurphy** [test-prof/test-prof#263]
### Tell us about your environment

**Ruby Version:**
ruby 2.7.6p219

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
rails ~> 6.1.0
rspec-rails ~> 5.0.0

**TestProf Version:**
test-prof ~> 1.2

### What did you do?
Installed ruby-prof 1.6.1 and tried to profile my specs

### What did you expect to happen?
For my specs to run

### What actually happened?
Got the following error:
```
ArgumentError:
  unknown keyword: :merge_fibers
 in /gems/test-prof-1.2.0/lib/test_prof/ruby_prof.rb:183:in `initialize'
```

According to `ruby-prof`s (changelog)[https://github.com/ruby-prof/ruby-prof/blob/master/CHANGES#L68], support for merge_fibers was removed in ruby-prof 1.4.0

**Comment by howdymatt** [comment]
I am also running into this issue.

**Comment by palkan** [comment]
Thanks for reporting, will fix soon.
