### ISSUE TITLE
AnyFixture disrupts database global state

### ISSUE THREAD

**Issue by gap777** [test-prof/test-prof#271]
### Tell us about your environment

**Ruby Version:** 3.2.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rails 7.0.6, RSpec 3.12.2, FactoryBot 6.2.1

**TestProf Version:** 1.2.2

### What did you do?

Convert DB-intensive setup from within a `describe` block to a shared context containing AnyFixture.

### What did you expect to happen?

The DB state would be established at the start of the shared context:

```
  RSpec.shared_context 'test', test: true do
    before(:all) do
      TestProf::AnyFixture.register(:test) do
      ...
```

and cleaned up at the end of the shared context:

```
   after(:all) do
      TestProf::AnyFixture.clean
   end
```

Leaving all tests outside of the shared context executing against a clean database. 

### What actually happened?

Other tests in the same model suite, and other tests in other suites, started failing (which assumed a clean db).

**Comment by palkan** [comment]
Have you included this context into multiple test files? If so, the reason could be the opposite: the block within the `.register` method is called once through the whole test suite; the `.clean` method wipes the database, but it doesn't reset the internal AnyFixture registry—it's only meant to clean the database in the end of the test run (or temporary in tests requiring a clean state).

**Comment by palkan** [comment]
Hey @gap777! Any updates on the issue?

**Comment by gap777** [comment]
@palkan Yes, we're including this setup from multiple files... is that contrary to your intentions? Are there any workarounds whereby we can get this:

* replace complex and slow DB setup via FactoryBot w/ AnyFixture
* use this setup across multiple tests and multiple test suites (files)
* have the DB restored after each test that uses it.

**Comment by palkan** [comment]
> have the DB restored after each test that uses it.

Not sure I get this one: you mean clean up database after each test/context?

Then, I think, you need [let_it_be](https://test-prof.evilmartians.io/recipes/let_it_be); AnyFixture is meant to populate data that is shared across files.
