### ISSUE TITLE
No after_all for rspec

### ISSUE THREAD

**Issue by d4rky-pl** [test-prof/test-prof#275]
### Tell us about your environment

**Ruby Version:**
3.1.3

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
rspec 3.12

**TestProf Version:**
1.2.3

### What did you do?
I tried using `after_all` in the rspec specs

### What did you expect to happen?
Feature parity with minitest

### What actually happened?
No feature parity, sad developer

**Comment by palkan** [comment]
> No feature parity, sad developer

In RSpec, there is already `after(:all)` which should suffice your needs. (And that's the reason why we don't have `after_all`). Maybe, I'm missing some use case when we need `after_all` and it must behave differently from `after(:all)`?

**Comment by palkan** [comment]
@d4rky-pl Ping

**Comment by d4rky-pl** [comment]
@palkan apologies, a recent family emergency made me drop everything I was actively working on.

I honestly can't remember anymore why I assumed I need it. Possibly it was just for DSL parity? (in which case `after_all` in rspec could just be an alias to `after(:all)`)

I'm going to close this issue until I'm working on Ruby backend topics again and see a good reason for this.
