### ISSUE TITLE
Issue trying to upgrade Rails 7.1.1

### ISSUE THREAD

**Issue by deivinsontejeda** [test-prof/test-prof#279]
### Tell us about your environment

**Ruby Version:** 3.2.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rspec, Rails 7.1.1

**TestProf Version:** 1.2.3

### What did you do?

Rails added these changes https://github.com/rails/rails/pull/45924 on multi-db config. In my process to upgrade to Rails 7.1.1 I found the following warning when run rspec: 
```
DEPRECATION WARNING: `connection_pool_list` currently only applies to connection pools in the current role (`writing`). In Rails 7.2, this method will apply to all known pools, regardless of role. To affect only those connections belonging to a specific role, pass the role name as an argument. To switch to the new behavior, pass `:all` as the role name.
```

In order to detect where the warning comes from, I added the following setting on my test environment.

```
config.active_support.deprecation = :raise
```

And found the full trace of this warning...
```
ActiveSupport::DeprecationException:
       DEPRECATION WARNING: `connection_pool_list` currently only applies to connection pools in the current role (`writing`). In Rails 7.2, this method will apply to all known pools, regardless of role. To affect only those connections belonging to a specific role, pass the role name as an argument. To switch to the new behavior, pass `:all` as the role name. (called from load at /usr/local/bundle/bin/rspec:25)
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all/adapters/active_record.rb:11:in `all_connections'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all/adapters/active_record.rb:34:in `begin_transaction'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all.rb:24:in `block in begin_transaction'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all.rb:125:in `block in run_hooks'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all.rb:90:in `run'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all.rb:125:in `run_hooks'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/before_all.rb:23:in `begin_transaction'
     # /usr/local/bundle/gems/test-prof-1.2.3/lib/test_prof/recipes/rspec/before_all.rb:28:in `block in before_all'
```

According the doc/changes introduce in this PR https://github.com/rails/rails/pull/45924. [This line](https://github.com/test-prof/test-prof/blob/master/lib/test_prof/before_all/adapters/active_record.rb#L11) should pass `:all` when call `connection_pool_list`.

Applying this change the warning has gone and our CI (+3k tests) is running ok

https://github.com/test-prof/test-prof/blob/bd8502e3a8f2bfdfcc259b2ac900d956c493b079/lib/test_prof/before_all/adapters/active_record.rb#L11

Happy hacking!

**Comment by palkan** [comment]
Thanks for the detailed report! Will fix it

**Comment by palkan** [comment]
> [This line](https://github.com/test-prof/test-prof/blob/master/lib/test_prof/before_all/adapters/active_record.rb#L11) should pass :all when call

I think, we should pass `:writing` (similarly to what [Rails uses in fixtures](https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/activerecord/lib/active_record/test_fixtures.rb#L209)), since we're only interested in connections which may introduce shared/dirty state.
