### ISSUE TITLE
Not getting any logging output for TestProf

### ISSUE THREAD

**Issue by chrismanderson** [test-prof/test-prof#282]
### Tell us about your environment

**Ruby Version:** 3.0.4

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Minitest

**TestProf Version:** 1.3.1

### What did you do?

I installed the gem with 

```
group :test do
  gem "test-prof", "~> 1.0"
end
```

I added 

```
TestProf.configure do |config|
  # the directory to put artifacts (reports) in ('tmp/test_prof' by default)
  config.output_dir = "tmp/test_prof"

  # use unique filenames for reports (by simply appending current timestamp)
  config.timestamps = true

  # color output
  config.color = true

  # where to write logs (defaults)
  config.output = $stdout
end
```

to my `test_helper.rb` file. 

I then ran 

`TEST_STACK_PROF=boot TEST_PROF_REPORT=with-bootsnap bin/rails t`

### What did you expect to happen?

I expected to get output of profiling into the tmp/test_prof folder.

### What actually happened?

I don't get any output. I see 

```
[TEST PROF INFO] StackProf (raw) enabled globally: mode – wall, target – boot
```

in the console logs when I run the tests, but I don't get any output when the suite completes nor see anything in the test_prof folder. I can't get output of any kind either in the command line or in the folder output.

Am I missing a step in configuration or setup here?

It's a Rails 6.1.7 app, with a fairly stock configuration.

**Comment by palkan** [comment]
Hey!

Are you using Minitest?

I'm afraid, boot time profiling is not supported in Minitest (and looks like like we miss this information in the docs—my bad).

What you can do is to drop this line somewhere in your `test_helper.rb` (after all the dependencies were loaded):

```ruby
TestProf::StackProf.dump("boot") if TestProf::StackProf.config.boot?
```

**Comment by palkan** [comment]
Closed as stale
