### ISSUE TITLE
Undefined method #present? when using test-prof w/o activesupport

### ISSUE THREAD

**Issue by ngarbezza** [test-prof/test-prof#284]
### Tell us about your environment

**Ruby Version:** 3.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** RSpec, No Rails

**TestProf Version:** 1.3.2 ()

### What did you do?

I upgraded to test-prof v1.3.2 and ran my tests locally.

### What did you expect to happen?

No test errors

### What actually happened?

I got failing tests because of:

```
Failure/Error: return true unless filters.present? && TestProf.rspec?
     
     NoMethodError:
       undefined method `present?' for {}:Hash
     
               return true unless filters.present? && TestProf.rspec?
                                         ^^^^^^^^^
     # ..../test-prof-1.3.2/lib/test_prof/before_all.rb:69:in `filters_apply?'
```

I suspect this is because I don't have activesupport in my project.

I'm happy to provide a fix to not depend on `.present?` for that particular case, let me know if that's ok.

**Comment by palkan** [comment]
> I'm happy to provide a fix to not depend on .present? for that particular case, let me know if that's ok.

Yeah, that would awesome!

Thanks for reporting

**Comment by ngarbezza** [comment]
Alright! I've created https://github.com/test-prof/test-prof/pull/287 . Please let me know what I'm missing, it's my first contribution to this repo.
