### ISSUE TITLE
Getting  undefined method `hooks_memory' for nil:NilClass

### ISSUE THREAD

**Issue by katpadi** [test-prof/test-prof#285]
### Tell us about your environment

**Ruby Version:** 3.0.6

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** RSpec

**TestProf Version:** 1.3.2

### What did you do?

I tried to run:
`TEST_MEM_PROF=rss bundle exec rspec spec/xxx_spec.rb`

### What did you expect to happen?
I expect no error.

### What actually happened?
I got an error like this:
```
/Users/foo/.rvm/gems/ruby-3.0.6/gems/test-prof-1.3.2/lib/test_prof/memory_prof/tracker.rb:54:in `group_finished': undefined method `hooks_memory' for nil:NilClass (NoMethodError)
from /Users/foo/.rvm/gems/ruby-3.0.6/gems/test-prof-1.3.2/lib/test_prof/memory_prof/rspec.rb:35:in `example_group_finished'
from /Users/foo/.rvm/gems/ruby-3.0.6/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:209:in `block in notify'
```

**Comment by palkan** [comment]
Thanks for the report!

Could you please share an example structure of the test file which results in the error? I mean smth like:

```ruby
describe "something" do
  it do
  end

  context do
    context do
      it do
      end
    end
  end
end
```

/cc @Vankiru

**Comment by MickPlaYer** [comment]
Hi, I got same exception.
But I figured it out that I can fix it by adding arg to `it` in my code.


``` diff ruby
    describe 'request' do
      subject(:request) { post :create, params: params }
-     it { is_expected.to be_successful }
+     it('abc') { is_expected.to be_successful }
    end
```

**Comment by palkan** [comment]
I wasn't able to reproduce it yet but I found some potential reason and pushed a fix to master. @katpadi @MickPlaYer Could you please give it a try and confirm if it works or not?

**Comment by MickPlaYer** [comment]
@palkan Yes the newest master fix the problem for my code, and it work perfectly!
