### ISSUE TITLE
Rails 7.2 deprecation output

### ISSUE THREAD

**Issue by mjankowski** [test-prof/test-prof#297]
Running the Rails 7.2.0.beta2, I see deprecation notice like...

```
ActiveSupport::DeprecationException:
  DEPRECATION WARNING: ActiveRecord::ConnectionAdapters::ConnectionPool#connection is deprecated
  and will be removed in Rails 8.0. Use #lease_connection instead.
```

Backtrace points back to here https://github.com/test-prof/test-prof/blob/v1.3.3/lib/test_prof/before_all/adapters/active_record.rb#L15

I think this is just a method rename on Rails side.

**Comment by palkan** [comment]
Thanks for reporting! Just in time for our new release. Will fix it.

**Comment by palkan** [comment]
Looks like it's more than just a deprecation: https://github.com/rails/rails/pull/50999#issuecomment-2150906497.

Gonna postpone the release for a bit.

**Comment by palkan** [comment]
It's fixed on master but the fix is intended for Rails `7-2-stable` (not `beta2`).

**Comment by mjankowski** [comment]
Updated to rails `7.2.0.beta3` and using test-prof `1.3.3.1` I still see the deprecation output ... but I also did not follow the linked issue closely.

Should the release of 7.2.0.beta3 by itself have resolved this - or does that release just enable the changes need on test-prof side?

**Comment by palkan** [comment]
> using test-prof 1.3.3.1

This release doesn't include the Rails 7.2 change. Please, try master version.
