### ISSUE TITLE
AnyFixture refind with default scope

### ISSUE THREAD

**Issue by mingan** [test-prof/test-prof#306]
### Tell us about your environment

Ruby 3.1.2, TestProf 1.4.1

### What did you do?

Updated TestProf from 1.3.3.1 to 1.4.1

### What did you expect to happen?

rspec to run as usually

### What actually happened?

rspec fails with not being able to re-find a fixture because of https://github.com/test-prof/test-prof/commit/b42880710fce0ec31d037b366baa4292d06ae624 forcing a find + the AR model having `default_scope` which excludes that particular record.

Removing the `default_scope` is not an acceptable solution. A workaround is 

```ruby
let(:excluded_record} { TestProf::AnyFixture.cached(:excluded_record) }
```

Still, I think the `default_scope` interaction should at least be highlighted in the documenation.

**Comment by palkan** [comment]
Thanks for reporting! We should actually use `unscoped`—fetching fixtures by primary keys shouldn't depend on default scopes.
